# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BnKavrC9qHPse_mzQ5WY5R5FGF6j3LEA
"""

import streamlit as st
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

st.title("Loan Approval Prediction")
st.write("Masukkan informasi berikut untuk memprediksi status pinjaman:")

model = pickle.load(open('best_model.pkl', 'rb'))

label_encoder = LabelEncoder()
imputer = SimpleImputer(strategy='median')

def preprocess_input(data):
    data['person_gender'] = label_encoder.fit_transform([data['person_gender']])[0]
    data['person_education'] = label_encoder.fit_transform([data['person_education']])[0]
    data['person_home_ownership'] = label_encoder.fit_transform([data['person_home_ownership']])[0]
    data['loan_intent'] = label_encoder.fit_transform([data['loan_intent']])[0]
    data['previous_loan_defaults_on_file'] = label_encoder.fit_transform([data['previous_loan_defaults_on_file']])[0]

    data_imputed = imputer.transform([data.values()])
    return data_imputed

person_gender = st.selectbox("Gender", ['Male', 'Female'])
person_education = st.selectbox("Education", ['High School', 'Undergraduate', 'Postgraduate'])
person_home_ownership = st.selectbox("Home Ownership", ['Own', 'Rent'])
loan_intent = st.selectbox("Loan Intent", ['Personal', 'Business', 'Education'])
previous_loan_defaults_on_file = st.selectbox("Previous Loan Defaults", ['Yes', 'No'])
person_age = st.number_input("Age", min_value=18, max_value=100, value=30)
person_income = st.number_input("Annual Income", min_value=0, value=50000)
person_emp_exp = st.number_input("Years of Employment", min_value=0, max_value=40, value=5)
loan_amnt = st.number_input("Loan Amount Requested", min_value=1000, value=10000)
loan_int_rate = st.number_input("Loan Interest Rate", min_value=0.0, max_value=100.0, value=5.0)
loan_percent_income = st.number_input("Loan as Percentage of Income", min_value=0.0, max_value=100.0, value=20.0)
cb_person_cred_hist_length = st.number_input("Credit History Length (years)", min_value=0, value=5)
credit_score = st.number_input("Credit Score", min_value=300, max_value=850, value=650)

if st.button('Predict Loan Approval'):
    input_data = pd.DataFrame({
        'person_age': [person_age],
        'person_gender': [person_gender],
        'person_education': [person_education],
        'person_income': [person_income],
        'person_emp_exp': [person_emp_exp],
        'person_home_ownership': [person_home_ownership],
        'loan_amnt': [loan_amnt],
        'loan_intent': [loan_intent],
        'loan_int_rate': [loan_int_rate],
        'loan_percent_income': [loan_percent_income],
        'cb_person_cred_hist_length': [cb_person_cred_hist_length],
        'credit_score': [credit_score],
        'previous_loan_defaults_on_file': [previous_loan_defaults_on_file]
    })

    processed_data = preprocess_input(input_data)

    prediction = model.predict(processed_data)
    if prediction[0] == 1:
        st.write("Pinjaman Anda Disetujui!")
    else:
        st.write("Pinjaman Anda Ditolak.")