# -*- coding: utf-8 -*-
"""UTS Model Deployment no 3 - Axel Dimas A/2702274015

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsLRGLrkOUzTncRXyS_aE8H1AZVuLmae
"""

def predict_loan_status(input_data):

    model = pickle.load(open('best_model.pkl', 'rb'))

    input_data = imputer.transform([input_data])

    prediction = model.predict(input_data)
    return prediction